### ISSUE TITLE
Identifying unique counts of a medication from a single codelist

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/databuilder#192] opened 2021-11-03 16:46 UTC
There are various measures of prescribing which broadly are based on identifying people on specific groups of medications (e.g. 2 or more meds from this long list of 30 meds in a class) or "polypharmacy" (on 4 or more unique medications).

As an example the BSA medication safety indicator `ACB02` ([docs)](https://www.nhsbsa.nhs.uk/sites/default/files/2019-08/Medication%20Safety%20-%20Indicators%20Specification%20%28Aug19%29.pdf)

> Patients aged 18 or over in the prescription month concurrently prescribed 1 or more medicines for dementia and 1 or more medicines which have moderate or high anticholinergic activity 

In cohort extractor I'd like to give it the the single codelist described in docs and return a count of unique medications.

In our current cohort extractor I think you could do this by creating individual codelists for every single medicines and counting them all and then working out how many unique in the period but it would be much better if done in cohort extractor. On a quick brainstorm there are potentially two strategies on how this might work in cohort-extractor-v2

1. Straight up count unique returns
Potentially incorporate something like count distinct or `nunique` from pandas. This would give straight up number however when cohort extractor executes it looks at AMP or VMP data. Therefore we would count unique presentations of medications e.g. tablet and a liquid would count as unique. Generally speaking we wouldn't care about this uniqueness and examples above care about the uniqueness in the VTM.  I'm not sure how we could use `nùnique` to work out unique VTMs when running on VMP/AMP data without extracting actual presnetations?

2. Categorise then count
In v1 we have a method of  `categorised_as` ([docs](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.categorised_as)) although we have used it sparingly (see [smoking example](https://github.com/opensafely/risk-prediction-research/blob/405b196fc053e2461e5c15b2583d80343ccd4c06/analysis/study_definition.py#L213)). Potentially this might work where codelists are categorised and then you can count unique instances of the category?

This is related to an open issue on [OpenCodelists here](https://github.com/opensafely-core/opencodelists/issues/507) and I'm sure others.

**Comment by brianmackenna** [comment] 2022-10-24 14:28
In short I would like to know.......

how many medicines a patient is currently prescribed (ignore #159 for purposes of this issue!)

**Comment by evansd** [comment] 2022-10-31 12:34
I think this would be solved by adding the proposed [`count_unique`](https://github.com/opensafely-core/databuilder/issues/546) method to ehrQL.

Given the composability of ehrQL this could be combined with other operations depending on your needs, for instance:

 * **Count the number of distinct presentations prescribed:**
   ```py
   medications.dmd_code.count_distinct()
   ```

 * **Count the number of _types_ of medication:**
   ```py
   medications.dmd_code.to_category(codelist.category).count_distinct()
   ```

 * **Count the number of months in which a medication was prescribed:**
   ```py
   medications \
     .take(medications.dmd_code.is_in(codelist)) \
     .date.to_first_of_month() \
     .count_distinct()
   ```

And so on ...

**Comment by brianmackenna** [comment] 2022-11-01 14:00
This looks really useful.

Just to add that myself and @evansd also discussed adding some additional dm+d maps to the backend to help with things like VMP/AMP->VTM.

I think we have enough information for now and can return to this when doing a specific research project related to it or upgrading `with_these_medications`

**Comment by benbc** [comment] 2022-12-02 09:55
This is a duplicate of #546. I'll add a note on that issue to point out this specific use case.

**Closed by benbc** 2022-12-02 09:55 UTC
